from version import palmapy_version
from config import (
    DEFAULT_ACCESS_CONTROL_MAX_AGE,
    DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN
)

# API 
API_VERSION = palmapy_version
API_VERSION_HTTP_HEADER_NAME = "Palmapy-Server-Version"
API_KEY_HTTP_HEADER_NAME = "Palmapy-Server-Api-Key"

# ERRORS
ERROR_API = "api_error"
ERROR_INVALID_REQUEST = "invalid_request_error"

# CONTENT TYPE
HTTP_DEFAULT_CONTENT_TYPE = "application/json"

# CORS HTTP VALUES
HTTP_DEFAULT_ACCESS_CONTROL_MAX_AGE = DEFAULT_ACCESS_CONTROL_MAX_AGE
HTTP_DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN = DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN
HTTP_DEFAULT_ACCESS_CONTROL_ALLOW_HEADERS = API_KEY_HTTP_HEADER_NAME + ", Access-Control-Allow-Headers, Access-Control-Allow-Origin, Access-Control-Max-Age, Content-Type, Authorization"

# CORS HTTP HEADERS NAMES
HEADER_DEFAULT_ACCESS_CONTROL_MAX_AGE = "Access-Control-Max-Age"
HEADER_DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN = "Access-Control-Allow-Origin"
HEADER_DEFAULT_ACCESS_CONTROL_ALLOW_HEADERS = "Access-Control-Allow-Headers"